// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATPHbmslju7bOnfMZ88LROPTztyMqgLk8',
    appId: '1:7424665061:web:1ea1bf558c92c7d09b7b0c',
    messagingSenderId: '7424665061',
    projectId: 'masrofy-fe92b',
    authDomain: 'masrofy-fe92b.firebaseapp.com',
    storageBucket: 'masrofy-fe92b.firebasestorage.app',
    measurementId: 'G-NEKESLDYFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHHJC4SemkWmm2pbTfG2cWi4V3AtyoC3c',
    appId: '1:7424665061:android:23630b19a9b6829a9b7b0c',
    messagingSenderId: '7424665061',
    projectId: 'masrofy-fe92b',
    storageBucket: 'masrofy-fe92b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoGicFSDT0XJPf0ziZEPG6j0Ddf44Tnr4',
    appId: '1:7424665061:ios:8bb46a906a19eace9b7b0c',
    messagingSenderId: '7424665061',
    projectId: 'masrofy-fe92b',
    storageBucket: 'masrofy-fe92b.firebasestorage.app',
    iosBundleId: 'com.example.masrofy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoGicFSDT0XJPf0ziZEPG6j0Ddf44Tnr4',
    appId: '1:7424665061:ios:8bb46a906a19eace9b7b0c',
    messagingSenderId: '7424665061',
    projectId: 'masrofy-fe92b',
    storageBucket: 'masrofy-fe92b.firebasestorage.app',
    iosBundleId: 'com.example.masrofy',
  );
}
